# Generated by Django 4.2.30 on 2026-09-22 16:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_jurisdiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncentiveProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('credit_type', models.CharField(choices=[('REBATE', 'Cash Rebate'), ('TRANSFERABLE_CREDIT', 'Transferable Tax Credit'), ('REFUNDABLE_CREDIT', 'Refundable Tax Credit')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, help_text='e.g. 0.30 for a 30% credit', max_digits=5)),
                ('cap_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit this program will pay out per project, if capped', max_digits=14, null=True)),
                ('qualified_subtypes', models.CharField(default='BTL,POST', max_length=100)),
                ('typical_monetization_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0'), help_text='Cash value per dollar of credit once sold/received, e.g. 0.90', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_programs', to='core.jurisdiction')),
            ],
            options={
                'ordering': ['jurisdiction', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIncentiveClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ESTIMATED', 'Estimated'), ('APPLIED', 'Application Filed'), ('UNDER_REVIEW', 'Under Audit/Review'), ('CERTIFIED', 'Certified'), ('RECEIVED', 'Funds Received')], default='ESTIMATED', max_length=20)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('funds_received_date', models.DateField(blank=True, null=True)),
                ('certified_qualified_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('certified_credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='incentives.incentiveprogram')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_claims', to='core.project')),
            ],
            options={
                'ordering': ['project', 'program'],
                'unique_together': {('project', 'program')},
            },
        ),
    ]
