# Generated by Django 4.2.30 on 2026-09-22 15:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(default='$', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('PRE_PRODUCTION', 'Pre-Production'), ('PRODUCTION', 'Production'), ('POST_PRODUCTION', 'Post-Production'), ('DELIVERED', 'Delivered'), ('DISTRIBUTION', 'Distribution'), ('CLOSED', 'Closed')], default='DEVELOPMENT', max_length=20)),
                ('budget_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('greenlit_date', models.DateField(blank=True, null=True)),
                ('wrap_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('functional_currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate_to_usd', models.DecimalField(decimal_places=6, max_digits=14)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
