# Generated by Django 4.2.30 on 2026-09-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jurisdiction'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='incurred_jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_lines', to='core.jurisdiction'),
        ),
    ]
