# Generated by Django 4.2.30 on 2026-09-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('THEATRICAL', 'Theatrical'), ('SVOD', 'SVOD License'), ('AVOD', 'AVOD License'), ('TV_LICENSE', 'TV License'), ('INTERNATIONAL', 'International Distribution'), ('MERCHANDISE', 'Merchandise/Ancillary')], max_length=20)),
                ('recognition_method', models.CharField(choices=[('POINT_IN_TIME', 'Point in Time'), ('STRAIGHT_LINE', 'Straight-Line Over Term'), ('MILESTONE', 'Milestone-Based')], max_length=20)),
                ('total_contract_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('license_start', models.DateField(blank=True, null=True)),
                ('license_end', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_contracts', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='revenue.revenuecontract')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueRecognitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_entries', to='revenue.revenuecontract')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.journalentry')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_entries', to='revenue.revenuemilestone')),
            ],
            options={
                'ordering': ['period_start'],
            },
        ),
    ]
