# Generated by Django 4.2.30 on 2026-09-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('net_proceeds_available', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.project')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entity_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('LLC', 'LLC'), ('FUND', 'Fund'), ('STUDIO', 'Studio/Financier')], default='INDIVIDUAL', max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WaterfallTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('tier_type', models.CharField(choices=[('RETURN_OF_CAPITAL', 'Return of Capital'), ('PREFERRED_RETURN', 'Preferred Return'), ('PROFIT_SPLIT', 'Profit Split')], max_length=20)),
                ('preferred_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('investor_share', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_tiers', to='core.project')),
            ],
            options={
                'ordering': ['project', 'order'],
                'unique_together': {('project', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_type', models.CharField(choices=[('EQUITY', 'Equity'), ('GAP', 'Gap Financing'), ('DEBT', 'Debt'), ('TAX_CREDIT_BRIDGE', 'Tax Credit Bridge Loan')], default='EQUITY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.investor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.project')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DistributionLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='investors.distribution')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_line_items', to='investors.investor')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='investors.waterfalltier')),
            ],
        ),
    ]
