# Generated by Django 4.2.30 on 2026-09-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Production Budget', max_length=120)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.project')),
            ],
            options={
                'ordering': ['project', '-version'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='ledger.account')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgeting.budget')),
            ],
            options={
                'ordering': ['account__code'],
                'unique_together': {('budget', 'account')},
            },
        ),
    ]
